# preview 라벨이 달린 PR에 대한 Docker Image 빌드 Action
name: PR Preview Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'qa-preview')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/uprise-fin/ci-sample:${{ github.event.pull_request.head.sha }}

      - name: PR Comment for link
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Preview URL: "http://ci-sample-${{ github.event.number }}.pr-ci-sample.dev.service.eks/"
            TailScale이 켜져 있는 경우에만 접속 가능합니다.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
