# Release 빌드 Action
name: Release Build
on:
  push:
    tags:
      - "v*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/uprise-fin/ci-sample:latest
            ghcr.io/uprise-fin/ci-sample:${{ github.ref_name }}

      - uses: Stockopedia/action-octommit@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            octommit.update()
              .org("uprise-fin")
              .repository("heybit-eks-apps")
              .sourceBranch("main")
              .outputBranch("main")
              .sourcePath("service-apps/ci-sample/values.yaml")
              .outputPath("service-apps/ci-sample/values.yaml")
              .set("image.tag", "${{ github.ref_name }}")
              .commit("chore: update image version of ci-sample to ${{ github.ref_name }}")
              .run();
